# Generated by Django 4.1 on 2022-09-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('signin', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=50)),
                ('funds', models.IntegerField(default=100000000)),
                ('score', models.IntegerField(default=0)),
                ('teamname', models.CharField(max_length=255)),
            ],
        ),
    ]
